### ISSUE TITLE
Ionic Pro build error

### ISSUE THREAD

**Issue by alejandromagnorsky** [gshigeto/ionic-environment-variables#16]
Trying to put my app in Ionic Pro after implementing this config I get the following error:

```
> pos-ionic3@0.0.1 build /usr/src/app
> MY_ENV=stag ionic-app-scripts build --prod

[06:24:05]  ionic-app-scripts 3.1.4 
[06:24:05]  build prod started ... 
[06:24:06]  clean started ... 
[06:24:06]  clean finished in 1 ms 
[06:24:06]  copy started ... 
[06:24:06]  deeplinks started ... 
[06:24:06]  deeplinks finished in 119 ms 
[06:24:06]  ngc started ... 
[06:24:14]  typescript: src/providers/api/api.ts, line: 3 
            Cannot find module '@app/env'. 

       L2:  import { Injectable } from '@angular/core';
       L3:  import { ENV } from '@app/env';

[06:24:14]  ionic-app-script task: "build" 
[06:24:14]  Error: The Angular AoT build failed. See the issues above 
Error: The Angular AoT build failed. See the issues above
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:232:55
    at step (/usr/src/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/usr/src/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/usr/src/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at 
npm info lifecycle pos-ionic3@0.0.1~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pos-ionic3@0.0.1 build: `MY_ENV=stag ionic-app-scripts build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pos-ionic3@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2017-12-01T06_24_14_284Z-debug.log
npm run build failed
Make sure your project has a build script in the package.json
Running after script...
$ clean-up
Cleaning up files...
Successful clean up
ERROR: Job failed: exit status 1
```

In my computer if I execute `npm run build` (which is what Ionic Pro runs) it works properly.

Thank you.

**Comment by Robinyo** [comment]
-> In my computer if I execute npm run build (which is what Ionic Pro runs) it works properly.

Sure, but that's a non `--prod` build (your not invoking -> ngc started ... ).

Try:

```
npm run clean
npm run build --prod
```

See:
- https://robferguson.org/blog/2017/11/22/working-with-typescript-webpack-and-ionic-3/
- https://robferguson.org/blog/2017/11/28/testing-your-ionic-3-app/
- https://github.com/Robinyo/big-top

**Comment by alejandromagnorsky** [comment]
Hi. Please note that npm run build is running:
`MY_ENV=stag ionic-app-scripts build --prod`
as indicated at the beginning of the error message. 
So, I don't need to include the --prod next to it. Still, if I run your suggested lines the result is the same: It works in my computer but not in Ionic Pro.

**Comment by alejandromagnorsky** [comment]
It might have been because my .gitignore included the `environments` folder. However, I switched to another solution already because modifying the `tsconfig.json` caused my autocompleted imports in Visual Code to have a wrong path.

**Comment by gshigeto** [comment]
Closing this issue
