### ISSUE TITLE
The Angular AoT build failed. typescript error

### ISSUE THREAD

**Issue by FanYeeChok** [gshigeto/ionic-environment-variables#18]
When run the command 
`ionic build --prod` 
cause the following error

```
Running app-scripts build: --prod
[11:23:37]  build prod started ...
[11:23:38]  clean started ...
[11:23:38]  clean finished in 206 ms
[11:23:38]  copy started ...
[11:23:44]  deeplinks started ...
[11:23:45]  deeplinks finished in 595 ms
[11:23:45]  ngc started ...
[11:24:11]  typescript error
            Error encountered resolving symbol values statically. Could not resolve @app/env relative to
            /Users/sme_academy10/Documents/hybrid/deployment/GERewards/src/pages/shared/reducers/index.ts., resolving
            symbol metaReducers in
            /Users/sme_academy10/Documents/hybrid/deployment/GERewards/src/pages/shared/reducers/index.ts, resolving
            symbol AppModule in /Users/sme_academy10/Documents/hybrid/deployment/GERewards/src/app/app.module.ts,
            resolving symbol AppModule in
            /Users/sme_academy10/Documents/hybrid/deployment/GERewards/src/app/app.module.ts, resolving symbol AppModule
            in /Users/sme_academy10/Documents/hybrid/deployment/GERewards/src/app/app.module.ts

Error: The Angular AoT build failed. See the issues above
    at /Users/sme_academy10/Documents/hybrid/deployment/GERewards/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Users/sme_academy10/Documents/hybrid/deployment/GERewards/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/sme_academy10/Documents/hybrid/deployment/GERewards/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/sme_academy10/Documents/hybrid/deployment/GERewards/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
```

`ionic info`

```
cli packages: (/Users/sme_academy10/.npm-packages/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.2.3 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v9.3.0
    npm        : 2.15.12
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by gshigeto** [comment]
Could you provide a repo for this error?

**Comment by rodriguesgm** [comment]
@FanYeeChok I had the same error but it was related with some typescript error that I got in one of my dependency. After solving the typescript error, the build ran ok. So, probably, you need to solve that typescript error you have before running the build --prod. Try running build --dev and it'll problably fail too.
just my 2 cents...

**Comment by FanYeeChok** [comment]
@rodriguesgm Do you mind to share which dependency/typescript error cause the issue?

**Comment by rafbgarcia** [comment]
I'm having a similar issue, but it's all related to `@ionic/app-scripts/dist/aot/aot-compiler.js`.

```
Running app-scripts build: --prod
[22:24:46]  build prod started ...
[22:24:46]  clean started ...
[22:24:46]  clean finished in 1 ms
[22:24:46]  copy started ...
[22:24:46]  deeplinks started ...
[22:24:46]  deeplinks finished in 37 ms
[22:24:46]  ngc started ...
[22:24:49]  typescript error
            Can't resolve all parameters for MyApp in /Users/rafa/natal-food/imoto-motoboys/src/app/app.component.ts:
            ([object Object], [object Object], [object Object], ?).

Error: The Angular AoT build failed. See the issues above
    at /Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/rafa/natal-food/imoto-motoboys/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
[22:24:49]  copy finished in 3.43 s
```

Does anyone know what this might be? Been trying to figure it out for 4 hours now 😞

**Comment by rafbgarcia** [comment]
Here is my `$ ionic info` fwiw:

```
cli packages: (/Users/rafa/.nvm/versions/node/v8.9.4/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/rafa/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by gshigeto** [comment]
@rafbgarcia, that seems like a dependency injection error in your app.component. You do not need to inject environments into components.

**Comment by rafbgarcia** [comment]
@gshigeto it's not, I just managed to get it solved, the error message is REALLY bad, check it out:

### Copy/paste of another response

For more info, see my answer here:
https://forum.ionicframework.com/t/issue-running-ionic-build-prod/120435/16

Apparently I can't `export default class`, this was the entire ******* issue.

My steps:

### Step 1

Create a new ionic project and make check whether `$ ionic build --prod` works.

It did work.

### Step 2

Try to make the build fail.

I achieved that creating a service and trying to use it in `app.component.ts`

```
import { Injectable } from '@angular/core'

@Injectable()
export default class Service {
  constructor() {}
}
```

### Step 3

Try to make the build pass.

Updated my service to do an `export class Service` instead of `export default class Service`

```
import { Injectable } from '@angular/core'

@Injectable()
export class Service {
  constructor() {}
}
```

It passed.

## Conclusion

Both errors were solved by that.

1- `app.component.ts` -> `Can't resolve all parameters for MyApp [...]`
2- `app.module.ts` -> `Unexpected value 'null' declared by the module 'AppModule in [...]`

**Comment by gshigeto** [comment]
Awesome! I am glad that you were able to get that figured out.
