### ISSUE TITLE
don't work ionic-angular@3.7.0 env.

### ISSUE THREAD

**Issue by rdlabo** [gshigeto/ionic-environment-variables#3]
I do.

```
git clone https://github.com/rdlabo/ionic-environment-variables.git
cd ionic-environment-variables
npm i
npm install ionic-angular@3.7.0 @ionic/app-scripts@3.0.0 @angular/core@4.4.3 @angular/common@4.4.3 @angular/compiler@4.4.3 @angular/compiler-cli@4.4.3 @angular/forms@4.4.3 @angular/http@4.4.3 @angular/platform-browser@4.4.3 @angular/platform-browser-dynamic@4.4.3 rxjs@5.4.3 zone.js@0.8.17 --save
ionic serve
```

and, this is error log.

```
There was an error in config file "/Users/sakakibara/dev/ionic-environment-variables/config/webpack.config.js". Using defaults instead.
TypeError: Cannot set property 'alias' of undefined
    at module.exports (/Users/sakakibara/dev/ionic-environment-variables/config/webpack.config.js:5:34)
    at Object.fillConfigDefaults (/Users/sakakibara/dev/ionic-environment-variables/node_modules/@ionic/app-scripts/dist/util/config.js:322:30)
    at Object.getWebpackConfig (/Users/sakakibara/dev/ionic-environment-variables/node_modules/@ionic/app-scripts/dist/webpack.js:194:44)
    at Object.buildJsSourceMaps (/Users/sakakibara/dev/ionic-environment-variables/node_modules/@ionic/app-scripts/dist/bundle.js:26:35)
    at /Users/sakakibara/dev/ionic-environment-variables/node_modules/@ionic/app-scripts/dist/transpile.js:117:51
    at transpileWorker (/Users/sakakibara/dev/ionic-environment-variables/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile (/Users/sakakibara/dev/ionic-environment-variables/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at /Users/sakakibara/dev/ionic-environment-variables/node_modules/@ionic/app-scripts/dist/build.js:106:82
```

**Comment by GabrielUlici** [comment]
If you are using only dev and prod then you can change the webpack.config.js to this:

`var path = require('path');
var useDefaultConfig = require('@ionic/app-scripts/config/webpack.config.js');

var procEnv = process.env.IONIC_ENV;

module.exports = function () {
  useDefaultConfig[procEnv].resolve.alias = {
    "@app/env": path.resolve('./src/environments/environment' + (process.env.IONIC_ENV === 'prod' ? '' : '.' + process.env.IONIC_ENV) + '.ts')
  };

  return useDefaultConfig;
};
`
